name: CI for PR and Push on Develop

on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - develop

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build and Unit Test
        run: ./gradlew build --no-daemon